version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    # depends_on:
    #   - api
    #   - client
    #   - worker
    #   - redis
    #   - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres_admin
      - POSTGRES_PASSWORD="mypassword1234"
  
  redis:
    image: 'redis:latest'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres_admin
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=mypassword1234
      - PGPORT=5432

    volumes:
      - /app/node_modules
      - ./server:/app

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
  
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres_admin
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=mypassword1234
      - PGPORT=5432