version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current

    working_directory: ~/app

    steps:
      - checkout
      - setup_remote_docker

      # Install dependencies
      - run:
          name: Install Dependencies
          command: docker build -t $DOCKERHUB_USERNAME/react-test -f ./client/Dockerfile.dev ./client

      # Run Tests
      - run:
          name: Run Tests
          command: docker run $DOCKERHUB_USERNAME/react-test npm test -- --coverage

  deploy_to_dockerhub:
    docker:
      - image: cimg/node:18.18.0

    working_directory: ~/app

    steps:
      - checkout

      # Build and push to DockerHub
      - run:
          name: Build and push to DockerHub
          command: |
            docker build -t $DOCKERHUB_USERNAME/multi-client ./client
            docker build -t $DOCKERHUB_USERNAME/multi-nginx ./nginx
            docker build -t $DOCKERHUB_USERNAME/multi-server ./server
            docker build -t $DOCKERHUB_USERNAME/multi-worker ./worker

            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/multi-client
            docker push $DOCKERHUB_USERNAME/multi-nginx
            docker push $DOCKERHUB_USERNAME/multi-server
            docker push $DOCKERHUB_USERNAME/multi-worker

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy_to_dockerhub:
          requires:
            - build
          filters:
            branches:
              only: main
